name: Build and Push Docker Container

on:
  push:
    branches:
      - main

jobs:
  build_and_push_container:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Login to Github Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.TOKEN }}
        
    - name: Build Nginx Docker Image
      run: |
        docker buildx build --platform linux/amd64 -t ghcr.io/andrewmiron/load-balancer:latest -f apps/nginx/Dockerfile .
        docker push ghcr.io/andrewmiron/load-balancer:latest
        
#     - name: Push Docker Image to Github Container Registry
#       run: |
#        docker push ghcr.io/andrewmiron/load-balancer:latest
